[theme]
base = "dark"

# Hoofdachtergrond: diep donkergroen
backgroundColor = "#0f1a0f"

# Secondary background: iets lichter groen voor velden en panelen
secondaryBackgroundColor = "#1f2e1f"

# Primary accent: paarsgroene gloed (knoppen, sliders, selectie)
primaryColor = "#6b3fa0"

# Tekstkleur
textColor = "#ffffff"

# Lettertype
font = "sans serif"
