# Supabase credentials voor lokaal testen
SUPABASE_URL = "https://rrnholgisiihwdwchelv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJybmhvbGdpc2lpaHdkd2NoZWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzODUxNDcsImV4cCI6MjA3NDk2MTE0N30.A4w-sJOqCA9Z7QxddRxAlYPLCT9lucWNOFddriNrB8c"
